/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBD.Batik.Frame.InternalFrame.Luaran;

import PBD.Batik.Frame.Koneksi;
import java.sql.*;
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author akbar
 */
public class MasterLuaran extends javax.swing.JInternalFrame {

    /**
     * Creates new form MasterLuaran
     */
    
    Connection conn;
    Statement cmd;
    ResultSet rs;
    String SQL;
    
    public MasterLuaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnPenjualanSedikit = new javax.swing.JButton();
        btnPenjualanBanyak = new javax.swing.JButton();
        btnPenjualan = new javax.swing.JButton();
        btnUmur = new javax.swing.JButton();
        btnGender = new javax.swing.JButton();
        btnPembelian = new javax.swing.JButton();
        btnPendapatan = new javax.swing.JButton();
        btnPengeluaran = new javax.swing.JButton();
        btnStok = new javax.swing.JButton();
        btnDaerah = new javax.swing.JButton();
        cbDaerah = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tglAwal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tglAkhir = new com.toedter.calendar.JDateChooser();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(38, 42, 65));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 182, 112));
        jLabel7.setText("Luaran Report");

        btnPenjualanSedikit.setBackground(new java.awt.Color(153, 255, 204));
        btnPenjualanSedikit.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPenjualanSedikit.setForeground(new java.awt.Color(0, 0, 0));
        btnPenjualanSedikit.setText("Penjualan Barang Tersedikit");
        btnPenjualanSedikit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanSedikitActionPerformed(evt);
            }
        });

        btnPenjualanBanyak.setBackground(new java.awt.Color(153, 255, 204));
        btnPenjualanBanyak.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPenjualanBanyak.setForeground(new java.awt.Color(0, 0, 0));
        btnPenjualanBanyak.setText("Penjualan Barang Terbanyak");
        btnPenjualanBanyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanBanyakActionPerformed(evt);
            }
        });

        btnPenjualan.setBackground(new java.awt.Color(153, 255, 204));
        btnPenjualan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPenjualan.setForeground(new java.awt.Color(0, 0, 0));
        btnPenjualan.setText("Laporan Penjualan");
        btnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanActionPerformed(evt);
            }
        });

        btnUmur.setBackground(new java.awt.Color(153, 255, 204));
        btnUmur.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUmur.setForeground(new java.awt.Color(0, 0, 0));
        btnUmur.setText("Penjualan Berdasarkan Umur");
        btnUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmurActionPerformed(evt);
            }
        });

        btnGender.setBackground(new java.awt.Color(153, 255, 204));
        btnGender.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnGender.setForeground(new java.awt.Color(0, 0, 0));
        btnGender.setText("Penjualan Berdasarkan Gender");
        btnGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenderActionPerformed(evt);
            }
        });

        btnPembelian.setBackground(new java.awt.Color(153, 255, 204));
        btnPembelian.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPembelian.setForeground(new java.awt.Color(0, 0, 0));
        btnPembelian.setText("Laporan Pembelian");
        btnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembelianActionPerformed(evt);
            }
        });

        btnPendapatan.setBackground(new java.awt.Color(153, 255, 204));
        btnPendapatan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPendapatan.setForeground(new java.awt.Color(0, 0, 0));
        btnPendapatan.setText("Laporan Pendapatan");
        btnPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendapatanActionPerformed(evt);
            }
        });

        btnPengeluaran.setBackground(new java.awt.Color(153, 255, 204));
        btnPengeluaran.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPengeluaran.setForeground(new java.awt.Color(0, 0, 0));
        btnPengeluaran.setText("Laporan Pengeluaran");
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });

        btnStok.setBackground(new java.awt.Color(153, 255, 204));
        btnStok.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnStok.setForeground(new java.awt.Color(0, 0, 0));
        btnStok.setText("Laporan Stok");
        btnStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokActionPerformed(evt);
            }
        });

        btnDaerah.setBackground(new java.awt.Color(153, 255, 204));
        btnDaerah.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDaerah.setForeground(new java.awt.Color(0, 0, 0));
        btnDaerah.setText("Penjualan Berdasarkan Daerah");
        btnDaerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaerahActionPerformed(evt);
            }
        });

        cbDaerah.setBackground(new java.awt.Color(255, 255, 255));
        cbDaerah.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cbDaerah.setForeground(new java.awt.Color(0, 0, 0));
        cbDaerah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Daerah---", "Provinsi", "Kabupaten", "Kecamatan", "Kelurahan" }));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal Awal");

        tglAwal.setDateFormatString("dd-MM-yyyy");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanggal Akhir");

        tglAkhir.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPenjualanSedikit, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPenjualanBanyak, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(tglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbDaerah, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDaerah, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGender, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(btnStok, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPenjualanSedikit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPenjualanBanyak, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDaerah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDaerah))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tglAwal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(tglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1020, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPenjualanSedikitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanSedikitActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            File ReportPenjualanSedikit = new File("src/PBD/Batik/Report/ReportPenjualanSedikit.jasper");
            JasperPrint JP = JasperFillManager.fillReport(ReportPenjualanSedikit.getPath(), null, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPenjualanSedikitActionPerformed

    private void btnPenjualanBanyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanBanyakActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            File ReportPenjualanSedikit = new File("src/PBD/Batik/Report/ReportPenjualanBanyak.jasper");
            JasperPrint JP = JasperFillManager.fillReport(ReportPenjualanSedikit.getPath(), null, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPenjualanBanyakActionPerformed

    private void btnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            HashMap hash = new HashMap(2);
            hash.put("tglAwal", tglAwal.getDate());
            hash.put("tglAkhir", tglAkhir.getDate());
            
            if(tglAwal.getDate() == null || tglAkhir.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Masukkan Tanggal Awal dan Akhir");
            } else {
                File ReportPenjualanSedikit = new File("src/PBD/Batik/Report/ReportPenjualan.jasper");
                JasperPrint JP = JasperFillManager.fillReport(ReportPenjualanSedikit.getPath(), hash, conn);
                JasperViewer.viewReport(JP, false);
            }
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPenjualanActionPerformed

    private void btnUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmurActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            File ReportUmurTermuda = new File("src/PBD/Batik/Report/ReportUmurTermuda.jasper");
            JasperPrint JP = JasperFillManager.fillReport(ReportUmurTermuda.getPath(), null, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnUmurActionPerformed

    private void btnGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenderActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            File ReportGender = new File("src/PBD/Batik/Report/ReportGender.jasper");
            JasperPrint JP = JasperFillManager.fillReport(ReportGender.getPath(), null, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnGenderActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembelianActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            HashMap hash = new HashMap(2);
            hash.put("tglAwal", tglAwal.getDate());
            hash.put("tglAkhir", tglAkhir.getDate());
            
            if(tglAwal.getDate() == null || tglAkhir.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Masukkan Tanggal Awal dan Akhir");
            } else {
                File ReportPembelian = new File("src/PBD/Batik/Report/ReportPembelian.jasper");
                JasperPrint JP = JasperFillManager.fillReport(ReportPembelian.getPath(), hash, conn);
                JasperViewer.viewReport(JP, false);
            }
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPembelianActionPerformed

    private void btnPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendapatanActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            HashMap hash = new HashMap(2);
            hash.put("tglAwal", tglAwal.getDate());
            hash.put("tglAkhir", tglAkhir.getDate());
            
            if(tglAwal.getDate() == null || tglAkhir.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Masukkan Tanggal Awal dan Akhir");
            } else {
                File ReportPendapatan = new File("src/PBD/Batik/Report/ReportPendapatan.jasper");
                JasperPrint JP = JasperFillManager.fillReport(ReportPendapatan.getPath(), hash, conn);
                JasperViewer.viewReport(JP, false);
            }
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPendapatanActionPerformed

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            HashMap hash = new HashMap(2);
            hash.put("tglAwal", tglAwal.getDate());
            hash.put("tglAkhir", tglAkhir.getDate());
            
            if(tglAwal.getDate() == null || tglAkhir.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Masukkan Tanggal Awal dan Akhir");
            } else {
                File ReportPengeluaran = new File("src/PBD/Batik/Report/ReportPengeluaran.jasper");
                JasperPrint JP = JasperFillManager.fillReport(ReportPengeluaran.getPath(), hash, conn);
                JasperViewer.viewReport(JP, false);
            }
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void btnStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            File ReportStok = new File("src/PBD/Batik/Report/ReportStok.jasper");
            JasperPrint JP = JasperFillManager.fillReport(ReportStok.getPath(), null, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnStokActionPerformed

    private void btnDaerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaerahActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            String pilih = cbDaerah.getSelectedItem().toString();
            
            if(pilih.equalsIgnoreCase("Provinsi")) {
                File ReportProvinsi = new File("src/PBD/Batik/Report/Daerah/ReportProvinsi.jasper");
                JasperPrint JP = JasperFillManager.fillReport(ReportProvinsi.getPath(), null, conn);
                JasperViewer.viewReport(JP, false);
                
            } else if(pilih.equalsIgnoreCase("Kabupaten")) {
                File ReportKecamatan = new File("src/PBD/Batik/Report/Daerah/ReportKabupaten.jasper");
                JasperPrint JP = JasperFillManager.fillReport(ReportKecamatan.getPath(), null, conn);
                JasperViewer.viewReport(JP, false);
                
            } else if(pilih.equalsIgnoreCase("Kecamatan")) {
                File ReportKecamatan = new File("src/PBD/Batik/Report/Daerah/ReportKecamatan.jasper");
                JasperPrint JP = JasperFillManager.fillReport(ReportKecamatan.getPath(), null, conn);
                JasperViewer.viewReport(JP, false);
                
            } else if(pilih.equalsIgnoreCase("Kelurahan")) {
                File ReportKecamatan = new File("src/PBD/Batik/Report/Daerah/ReportKelurahan.jasper");
                JasperPrint JP = JasperFillManager.fillReport(ReportKecamatan.getPath(), null, conn);
                JasperViewer.viewReport(JP, false);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih Daerah Terlebih Dahulu");
            }
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnDaerahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaerah;
    private javax.swing.JButton btnGender;
    private javax.swing.JButton btnPembelian;
    private javax.swing.JButton btnPendapatan;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton btnPenjualan;
    private javax.swing.JButton btnPenjualanBanyak;
    private javax.swing.JButton btnPenjualanSedikit;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton btnUmur;
    private javax.swing.JComboBox<String> cbDaerah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser tglAkhir;
    private com.toedter.calendar.JDateChooser tglAwal;
    // End of variables declaration//GEN-END:variables
}
