/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBD.Matkul.Pertemuan8;

/**
 *
 * @author akbar
 */
public class entriJobs extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public entriJobs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMinSalary = new javax.swing.JLabel();
        txMinSalary = new javax.swing.JTextField();
        txJobID = new javax.swing.JTextField();
        txJobTittle = new javax.swing.JTextField();
        txMaxSalary = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        labelJobTittle = new javax.swing.JLabel();
        labelJobID = new javax.swing.JLabel();
        labelMaxSalary = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        labelMinSalary.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelMinSalary.setForeground(new java.awt.Color(0, 0, 0));
        labelMinSalary.setText("MIN SALARY");

        txMinSalary.setBackground(new java.awt.Color(255, 255, 255));
        txMinSalary.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txMinSalary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txMinSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMinSalaryActionPerformed(evt);
            }
        });

        txJobID.setBackground(new java.awt.Color(255, 255, 255));
        txJobID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txJobID.setToolTipText("");
        txJobID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txJobID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txJobID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJobIDActionPerformed(evt);
            }
        });

        txJobTittle.setBackground(new java.awt.Color(255, 255, 255));
        txJobTittle.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txJobTittle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txJobTittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJobTittleActionPerformed(evt);
            }
        });

        txMaxSalary.setBackground(new java.awt.Color(255, 255, 255));
        txMaxSalary.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txMaxSalary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txMaxSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMaxSalaryActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 153));
        btnEdit.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/HR/Images/Icons/icons8_edit_24px.png"))); // NOI18N
        btnEdit.setText("Update");

        btnSave.setBackground(new java.awt.Color(153, 255, 153));
        btnSave.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/HR/Images/Icons/icons8_save_24px.png"))); // NOI18N
        btnSave.setText("Save");

        labelJobTittle.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelJobTittle.setForeground(new java.awt.Color(0, 0, 0));
        labelJobTittle.setText("JOB TITTLE");

        labelJobID.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelJobID.setForeground(new java.awt.Color(0, 0, 0));
        labelJobID.setText("JOB ID");

        labelMaxSalary.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelMaxSalary.setForeground(new java.awt.Color(0, 0, 0));
        labelMaxSalary.setText("MAX SALARY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMaxSalary)
                    .addComponent(labelJobTittle)
                    .addComponent(labelJobID)
                    .addComponent(labelMinSalary))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(92, 92, 92)
                        .addComponent(btnEdit))
                    .addComponent(txMinSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txJobID, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txJobTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txMaxSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJobID)
                    .addComponent(txJobID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJobTittle)
                    .addComponent(txJobTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMaxSalary)
                    .addComponent(txMaxSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinSalary)
                    .addComponent(txMinSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txMinSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMinSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMinSalaryActionPerformed

    private void txJobIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJobIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJobIDActionPerformed

    private void txJobTittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJobTittleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJobTittleActionPerformed

    private void txMaxSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMaxSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMaxSalaryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel labelJobID;
    private javax.swing.JLabel labelJobTittle;
    private javax.swing.JLabel labelMaxSalary;
    private javax.swing.JLabel labelMinSalary;
    private javax.swing.JTextField txJobID;
    private javax.swing.JTextField txJobTittle;
    private javax.swing.JTextField txMaxSalary;
    private javax.swing.JTextField txMinSalary;
    // End of variables declaration//GEN-END:variables
}
