/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBD.Batik.Frame;

import PBD.Batik.Frame.InternalFrame.Barang.MasterBarang;
import PBD.Batik.Frame.InternalFrame.Pegawai.MasterPegawai;
import PBD.Batik.Frame.InternalFrame.Pelanggan.MasterPelanggan;
import PBD.Batik.Frame.InternalFrame.Pemasok.MasterPemasok;
import PBD.Batik.Frame.InternalFrame.Pembelian.MasterPembelian;
import PBD.Batik.Frame.InternalFrame.Penjualan.MasterPenjualan;
import PBD.Batik.Frame.InternalFrame.Luaran.MasterLuaran;

/**
 *
 * @author akbar
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    MasterPegawai pegawai;
    MasterPelanggan pelanggan;
    MasterBarang barang;
    MasterPemasok pemasok;
    MasterPenjualan penjualan;
    MasterPembelian pembelian;
    MasterLuaran luaran;
    Menu menu;

    public MenuUtama() {
        initComponents();
        pegawai = new MasterPegawai();
        pelanggan = new MasterPelanggan();
        barang = new MasterBarang();
        pemasok = new MasterPemasok();
        penjualan = new MasterPenjualan();
        pembelian = new MasterPembelian();
        luaran = new MasterLuaran();
        
        menu = new Menu();
        if (!menu.isVisible()) {
            jDesktopPane1.add(menu);
            menu.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPegawai = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnPenjualan = new javax.swing.JButton();
        btnLuaran = new javax.swing.JButton();
        btnPemasok = new javax.swing.JButton();
        btnPembelian = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 720));

        btnPegawai.setBackground(new java.awt.Color(38, 42, 65));
        btnPegawai.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnPegawai.setForeground(new java.awt.Color(97, 97, 97));
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/Batik/Images/Icons/icons8_staff_48px.png"))); // NOI18N
        btnPegawai.setText("Pegawai");
        btnPegawai.setBorder(null);
        btnPegawai.setContentAreaFilled(false);
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(38, 42, 65));
        btnMenu.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(97, 97, 97));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/Batik/Images/Icons/icons8_dashboard_layout_48px.png"))); // NOI18N
        btnMenu.setText("Menu Utama");
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnPelanggan.setBackground(new java.awt.Color(38, 42, 65));
        btnPelanggan.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnPelanggan.setForeground(new java.awt.Color(97, 97, 97));
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/Batik/Images/Icons/icons8_user_48px.png"))); // NOI18N
        btnPelanggan.setText("Pelanggan");
        btnPelanggan.setBorder(null);
        btnPelanggan.setContentAreaFilled(false);
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(38, 42, 65));
        btnBarang.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnBarang.setForeground(new java.awt.Color(97, 97, 97));
        btnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/Batik/Images/Icons/icons8_front_view_48px.png"))); // NOI18N
        btnBarang.setText("Barang");
        btnBarang.setBorder(null);
        btnBarang.setContentAreaFilled(false);
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnPenjualan.setBackground(new java.awt.Color(38, 42, 65));
        btnPenjualan.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnPenjualan.setForeground(new java.awt.Color(97, 97, 97));
        btnPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/Batik/Images/Icons/icons8_shopping_cart_48px.png"))); // NOI18N
        btnPenjualan.setText("Penjualan");
        btnPenjualan.setBorder(null);
        btnPenjualan.setContentAreaFilled(false);
        btnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanActionPerformed(evt);
            }
        });

        btnLuaran.setBackground(new java.awt.Color(38, 42, 65));
        btnLuaran.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnLuaran.setForeground(new java.awt.Color(97, 97, 97));
        btnLuaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/Batik/Images/Icons/icons8_audit_48px.png"))); // NOI18N
        btnLuaran.setText("Luaran");
        btnLuaran.setBorder(null);
        btnLuaran.setContentAreaFilled(false);
        btnLuaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuaranActionPerformed(evt);
            }
        });

        btnPemasok.setBackground(new java.awt.Color(38, 42, 65));
        btnPemasok.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnPemasok.setForeground(new java.awt.Color(97, 97, 97));
        btnPemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/Batik/Images/Icons/icons8_package_48px.png"))); // NOI18N
        btnPemasok.setText("Pemasok");
        btnPemasok.setBorder(null);
        btnPemasok.setContentAreaFilled(false);
        btnPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemasokActionPerformed(evt);
            }
        });

        btnPembelian.setBackground(new java.awt.Color(38, 42, 65));
        btnPembelian.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnPembelian.setForeground(new java.awt.Color(97, 97, 97));
        btnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PBD/Batik/Images/Icons/icons8_supplier_48px.png"))); // NOI18N
        btnPembelian.setText("Pembelian");
        btnPembelian.setBorder(null);
        btnPembelian.setContentAreaFilled(false);
        btnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembelianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPembelian)
                    .addComponent(btnPemasok)
                    .addComponent(btnMenu)
                    .addComponent(btnLuaran)
                    .addComponent(btnPenjualan)
                    .addComponent(btnBarang)
                    .addComponent(btnPelanggan)
                    .addComponent(btnPegawai))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnMenu)
                .addGap(38, 38, 38)
                .addComponent(btnPegawai)
                .addGap(39, 39, 39)
                .addComponent(btnPelanggan)
                .addGap(41, 41, 41)
                .addComponent(btnBarang)
                .addGap(42, 42, 42)
                .addComponent(btnPemasok)
                .addGap(39, 39, 39)
                .addComponent(btnPenjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnPembelian)
                .addGap(38, 38, 38)
                .addComponent(btnLuaran)
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));
        jPanel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1020, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!pegawai.isVisible()) {
            jDesktopPane1.add(pegawai);
            pegawai.setVisible(true);
            penjualan.dispose();
            pembelian.dispose();
            pelanggan.dispose();
            barang.dispose();
            pemasok.dispose();
            luaran.dispose();
        }
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.add(menu);
        menu.setVisible(true);
        pegawai.dispose();
        penjualan.dispose();
        pembelian.dispose();
        pelanggan.dispose();
        barang.dispose();
        pemasok.dispose();
        luaran.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!penjualan.isVisible()) {
            jDesktopPane1.add(penjualan);
            penjualan.setVisible(true);
            pegawai.dispose();
            pelanggan.dispose();
            barang.dispose();
            pemasok.dispose();
            pembelian.dispose();
            luaran.dispose();
        }
    }//GEN-LAST:event_btnPenjualanActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!pelanggan.isVisible()) {
            jDesktopPane1.add(pelanggan);
            pelanggan.setVisible(true);
            pegawai.dispose();
            penjualan.dispose();
            barang.dispose();
            pemasok.dispose();
            pembelian.dispose();
            luaran.dispose();
        }
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!barang.isVisible()) {
            jDesktopPane1.add(barang);
            barang.setVisible(true);
            pegawai.dispose();
            penjualan.dispose();
            pelanggan.dispose();
            pemasok.dispose();
            pembelian.dispose();
            luaran.dispose();
        }
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemasokActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!pemasok.isVisible()) {
            jDesktopPane1.add(pemasok);
            pemasok.setVisible(true);
            pegawai.dispose();
            penjualan.dispose();
            pelanggan.dispose();
            barang.dispose();
            pembelian.dispose();
            luaran.dispose();
        }
    }//GEN-LAST:event_btnPemasokActionPerformed

    private void btnLuaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuaranActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!luaran.isVisible()) {
            jDesktopPane1.add(luaran);
            luaran.setVisible(true);
            pegawai.dispose();
            penjualan.dispose();
            pelanggan.dispose();
            barang.dispose();
            pembelian.dispose();
        }
    }//GEN-LAST:event_btnLuaranActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembelianActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!pembelian.isVisible()) {
            jDesktopPane1.add(pembelian);
            pembelian.setVisible(true);
            pegawai.dispose();
            pelanggan.dispose();
            barang.dispose();
            pemasok.dispose();
            luaran.dispose();
        }
    }//GEN-LAST:event_btnPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnLuaran;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnPemasok;
    private javax.swing.JButton btnPembelian;
    private javax.swing.JButton btnPenjualan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
