/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBD.Batik.Frame.InternalFrame.Pemasok;

import PBD.Batik.Frame.Koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akbar
 */
public class MasterPemasok extends javax.swing.JInternalFrame {

    /**
     * Creates new form MasterPegawai
     */
    Connection conn;
    Statement cmd;
    ResultSet rs;
    DefaultTableModel tmPemasok;
    String SQL;
    
    Statement cmd1;
    ResultSet rs1;
    
    public MasterPemasok() {
        initComponents();
        
        loadIDPemasok();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }
    
    private void loadIDPemasok(){
        try {
            conn = Koneksi.getKoneksi();
            SQL = "SELECT * FROM pemasok";
            cmd = conn.createStatement();
            rs = cmd.executeQuery(SQL);
            cbIDPemasok.removeAllItems();
            cbIDPemasok.addItem("Pilih ID Pemasok");
            while(rs.next()){
                String cid = rs.getString("id_pemasok");
                cbIDPemasok.addItem(cid);
            }
            
        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        }
    }
    
    private void showTabel() {
        try {
            conn = Koneksi.getKoneksi();
            
            cmd = conn.createStatement();
            rs = cmd.executeQuery("SELECT * FROM pemasok ORDER BY id_pemasok ASC");
            
            //Setting kolom dari DefaultTableModel
            tmPemasok = new DefaultTableModel(new String[] {"ID_PEMASOK", "NAMA_PEMASOK", "ALMT_PEMASOK", "TELP_PEMASOK"},0);
            
            //Pindah isi dari result set ke dalam DefaultTableModel
            if (rs.next()) {
                do {                    
                    tmPemasok.addRow(new Object[] {rs.getString("ID_PEMASOK"), rs.getString("NAMA_PEMASOK"), 
                        rs.getString("ALMT_PEMASOK"), rs.getString("TELP_PEMASOK")});
                } while (rs.next());
                
            } else {
                System.out.println("Data tidak ada");
            }
            
            tbPemasok.setDefaultEditor(Object.class, null);
            
            tbPemasok.setModel(tmPemasok);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }
    
    private String cekPemasok(int angka) {
        String pemasok = null;
        try {
            switch(angka) {
                case 1:
                    cmd1 = conn.createStatement();
                    rs1 = cmd1.executeQuery("SELECT nama_pemasok FROM pemasok WHERE id_pemasok = '" + cbIDPemasok.getSelectedItem().toString() + "' ");
                    if (rs1 == null) {

                    } else {
                        while(rs1.next()) {
                            pemasok = rs1.getString("nama_pemasok");
                        }
                    }
                break;
                
                case 2:
                    cmd1 = conn.createStatement();
                    rs1 = cmd1.executeQuery("SELECT almt_pemasok FROM pemasok WHERE id_pemasok = '" + cbIDPemasok.getSelectedItem().toString() + "' ");
                    if (rs1 == null) {

                    } else {
                        while(rs1.next()) {
                            pemasok = rs1.getString("almt_pemasok");
                        }
                    }
                break;
                
                case 3:
                    cmd1 = conn.createStatement();
                    rs1 = cmd1.executeQuery("SELECT telp_pemasok FROM pemasok WHERE id_pemasok = '" + cbIDPemasok.getSelectedItem().toString() + "' ");
                    if (rs1 == null) {

                    } else {
                        while(rs1.next()) {
                            pemasok = rs1.getString("telp_pemasok");
                        }
                    }
                break;
            }
            
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
        return pemasok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        labNamaPemasok = new javax.swing.JLabel();
        labAlamatPemasok = new javax.swing.JLabel();
        labIDPemasok = new javax.swing.JLabel();
        labTelpPemasok = new javax.swing.JLabel();
        txNamaPemasok = new javax.swing.JTextField();
        txAlamatPemasok = new javax.swing.JTextField();
        txTelpPemasok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        cbIDPemasok = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPemasok = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnClear1 = new javax.swing.JButton();
        btnTambahData = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        labNamaPemasok1 = new javax.swing.JLabel();
        txNamaPemasok1 = new javax.swing.JTextField();
        labAlamatPemasok1 = new javax.swing.JLabel();
        txAlamatPemasok1 = new javax.swing.JTextField();
        labTelpPemasok1 = new javax.swing.JLabel();
        txTelpPemasok1 = new javax.swing.JTextField();

        setBorder(null);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(38, 42, 65));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 0));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        labNamaPemasok.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labNamaPemasok.setForeground(new java.awt.Color(255, 255, 255));
        labNamaPemasok.setText("Nama Pemasok");

        labAlamatPemasok.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labAlamatPemasok.setForeground(new java.awt.Color(255, 255, 255));
        labAlamatPemasok.setText("Alamat Pemasok");

        labIDPemasok.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labIDPemasok.setForeground(new java.awt.Color(255, 255, 255));
        labIDPemasok.setText("ID Pemasok");

        labTelpPemasok.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labTelpPemasok.setForeground(new java.awt.Color(255, 255, 255));
        labTelpPemasok.setText("Telepon Pemasok");

        txNamaPemasok.setBackground(new java.awt.Color(255, 255, 255));
        txNamaPemasok.setForeground(new java.awt.Color(0, 0, 0));

        txAlamatPemasok.setBackground(new java.awt.Color(255, 255, 255));
        txAlamatPemasok.setForeground(new java.awt.Color(0, 0, 0));

        txTelpPemasok.setBackground(new java.awt.Color(255, 255, 255));
        txTelpPemasok.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 182, 112));
        jLabel7.setText("Data Pemasok");

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cbIDPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIDPemasokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labNamaPemasok)
                            .addComponent(labAlamatPemasok)
                            .addComponent(labTelpPemasok)
                            .addComponent(labIDPemasok))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbIDPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txTelpPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlamatPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNamaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(381, 381, 381))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnUpdate)
                .addGap(48, 48, 48)
                .addComponent(btnDelete)
                .addGap(33, 33, 33)
                .addComponent(btnClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labIDPemasok)
                    .addComponent(cbIDPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labNamaPemasok))
                    .addComponent(txNamaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labAlamatPemasok))
                    .addComponent(txAlamatPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labTelpPemasok))
                    .addComponent(txTelpPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(184, 184, 184))
        );

        jTabbedPane1.addTab("Master", jPanel1);

        tbPemasok.setBackground(new java.awt.Color(38, 42, 65));
        tbPemasok.setForeground(new java.awt.Color(255, 255, 255));
        tbPemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pemasok", "Nama Pemasok", "Alamat Pemasok", "Telepon Pemasok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPemasok.setGridColor(new java.awt.Color(255, 255, 255));
        tbPemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPemasokMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPemasok);

        jTabbedPane1.addTab("Tabel", jScrollPane2);

        jPanel2.setBackground(new java.awt.Color(38, 42, 65));

        btnClear1.setBackground(new java.awt.Color(255, 0, 0));
        btnClear1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnClear1.setForeground(new java.awt.Color(0, 0, 0));
        btnClear1.setText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        btnTambahData.setBackground(new java.awt.Color(0, 255, 0));
        btnTambahData.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnTambahData.setForeground(new java.awt.Color(0, 0, 0));
        btnTambahData.setText("Tambah Data");
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(246, 182, 112));
        jLabel8.setText("Data Pemasok");

        labNamaPemasok1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labNamaPemasok1.setForeground(new java.awt.Color(255, 255, 255));
        labNamaPemasok1.setText("Nama Pemasok");

        txNamaPemasok1.setBackground(new java.awt.Color(255, 255, 255));
        txNamaPemasok1.setForeground(new java.awt.Color(0, 0, 0));

        labAlamatPemasok1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labAlamatPemasok1.setForeground(new java.awt.Color(255, 255, 255));
        labAlamatPemasok1.setText("Alamat Pemasok");

        txAlamatPemasok1.setBackground(new java.awt.Color(255, 255, 255));
        txAlamatPemasok1.setForeground(new java.awt.Color(0, 0, 0));

        labTelpPemasok1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labTelpPemasok1.setForeground(new java.awt.Color(255, 255, 255));
        labTelpPemasok1.setText("Telepon Pemasok");

        txTelpPemasok1.setBackground(new java.awt.Color(255, 255, 255));
        txTelpPemasok1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labNamaPemasok1)
                                    .addComponent(labTelpPemasok1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labAlamatPemasok1))
                                .addGap(120, 120, 120)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txTelpPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txAlamatPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txNamaPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnTambahData)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear1)))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labNamaPemasok1))
                    .addComponent(txNamaPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txAlamatPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labAlamatPemasok1))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labTelpPemasok1))
                    .addComponent(txTelpPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear1)
                    .addComponent(btnTambahData))
                .addGap(253, 253, 253))
        );

        jTabbedPane1.addTab("Tambah Data", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        showTabel();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tbPemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPemasokMouseClicked
        // TODO add your handling code here:
        int index = tbPemasok.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2) {
            
            cbIDPemasok.setSelectedItem(tbPemasok.getValueAt(index, 0).toString());
            txNamaPemasok.setText(tbPemasok.getValueAt(index, 1).toString());
            txAlamatPemasok.setText(tbPemasok.getValueAt(index, 2).toString());
            txTelpPemasok.setText(tbPemasok.getValueAt(index, 3).toString());
        }
    }//GEN-LAST:event_tbPemasokMouseClicked

    private void clear() {
        cbIDPemasok.setSelectedIndex(0);
        txNamaPemasok.setText("");
        txAlamatPemasok.setText("");
        txTelpPemasok.setText("");
        
        txNamaPemasok1.setText("");
        txAlamatPemasok1.setText("");
        txTelpPemasok1.setText("");
    }
    
    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            CallableStatement call = conn.prepareCall("{call INS_PEMASOK(?,?,?)}");
            call.setString(1, txNamaPemasok1.getText());
            call.setString(2, txAlamatPemasok1.getText());
            call.setString(3, txTelpPemasok1.getText());
            call.execute();
            
//            SQL = "INSERT INTO pemasok (id_pemasok, nama_pemasok, almt_pemasok, telp_pemasok) VALUES ("
//            + " gen_id('pemasok'), "
//            + "'" + txNamaPemasok1.getText() + "',"
//            + "'" + txAlamatPemasok1.getText() + "',"
//            + "'" + txTelpPemasok1.getText() + "')";
//            cmd = conn.createStatement();
//            cmd.executeUpdate(SQL);
            JOptionPane.showMessageDialog(this, "Success");

            clear();
            showTabel();
            loadIDPemasok();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            CallableStatement call = conn.prepareCall("{call UPD_PEMASOK(?,?,?)}");
            call.setString(1, "nama");
            call.setString(2, cbIDPemasok.getSelectedItem().toString());
            call.setString(3, txNamaPemasok.getText());
            call.execute();
            
            CallableStatement cal2 = conn.prepareCall("{call UPD_PEMASOK(?,?,?)}");
            cal2.setString(1, "almt");
            cal2.setString(2, cbIDPemasok.getSelectedItem().toString());
            cal2.setString(3, txAlamatPemasok.getText());
            cal2.execute();
            
            CallableStatement cal3 = conn.prepareCall("{call UPD_PEMASOK(?,?,?)}");
            cal3.setString(1, "telepon");
            cal3.setString(2, cbIDPemasok.getSelectedItem().toString());
            cal3.setString(3, txTelpPemasok.getText());
            cal3.execute();
            
//            SQL = "UPDATE pemasok SET "
//                    + "nama_pemasok = " + "'" + txNamaPemasok.getText() + "',"
//                    + "almt_pemasok = " + "'" + txAlamatPemasok.getText() + "',"
//                    + "telp_pemasok = " + "'" + txTelpPemasok.getText() + "'"
//                    + "WHERE id_pemasok = '" + cbIDPemasok.getSelectedItem().toString() + "'";
//            cmd = conn.createStatement();
//            cmd.executeUpdate(SQL);
            JOptionPane.showMessageDialog(this, "Success");
            showTabel();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Failed: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int jawab = JOptionPane.showConfirmDialog(this, "Silakan Konfirmasi?");
            
            switch(jawab){
                case JOptionPane.YES_OPTION:
                    CallableStatement call = conn.prepareCall("{call DEL_PEMASOK(?)}");
                    call.setString(1, cbIDPemasok.getSelectedItem().toString());
                    call.execute();
                    
//                    SQL = "DELETE pemasok WHERE id_pemasok = '" + cbIDPemasok.getSelectedItem().toString() + "'";
//                    cmd = conn.createStatement();
//                    cmd.executeUpdate(SQL);
                    
                    JOptionPane.showMessageDialog(this, "Success");
                    showTabel();
                    loadIDPemasok();
                    clear();
                    break;
                    
                case JOptionPane.NO_OPTION:
                    break;
                    
                case JOptionPane.CANCEL_OPTION:
                    break;
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void cbIDPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIDPemasokActionPerformed
        // TODO add your handling code here:
        txNamaPemasok.setText(cekPemasok(1));
        txAlamatPemasok.setText(cekPemasok(2));
        txTelpPemasok.setText(cekPemasok(3));
    }//GEN-LAST:event_cbIDPemasokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbIDPemasok;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labAlamatPemasok;
    private javax.swing.JLabel labAlamatPemasok1;
    private javax.swing.JLabel labIDPemasok;
    private javax.swing.JLabel labNamaPemasok;
    private javax.swing.JLabel labNamaPemasok1;
    private javax.swing.JLabel labTelpPemasok;
    private javax.swing.JLabel labTelpPemasok1;
    private javax.swing.JTable tbPemasok;
    private javax.swing.JTextField txAlamatPemasok;
    private javax.swing.JTextField txAlamatPemasok1;
    private javax.swing.JTextField txNamaPemasok;
    private javax.swing.JTextField txNamaPemasok1;
    private javax.swing.JTextField txTelpPemasok;
    private javax.swing.JTextField txTelpPemasok1;
    // End of variables declaration//GEN-END:variables
}
